### PR TITLE
Disable options that are not needed on Braswell

### PR DESCRIPTION
**Pull request by snsmac**

### CODE REVIEW

**Comment by reynhout** [comment]
@snsmac Will these changes have implications on upcoming AMD Chromebooks?

**Comment by snsmac** [comment]
@reynhout I only changed the braswell config.
 I see no reason why you would run an kernel for braswell system on a Chromebook that's not based on a braswell cpu

**Comment by reynhout** [comment]
The goal is to re-unify the kernel packages for all supported hardware. Braswell is divergent right now because there are kernel config options with are mutually exclusive with Bay Trail options. This is hopefully temporary.

**Comment by snsmac** [comment]
Oh, I didn't knew that it is planned to unify the kernel

**Comment by reynhout** [comment]
@snsmac If we can show a performance or significant space advantage in having separate kernels, we would definitely consider it. It adds complication in the build process, but if it's worthwhile...

Presently the only reason they are split is to avoid platform-specific incompatibilities, or to allow some platforms to advance to a new kernel versions while others are kept back pending bugfixes.

**Pull request closed without merging**
